export const POKEMON_TYPES = [
  {
    name: 'normal',
    background: 'bg-stone-400',
    backgroundOverlay: 'after:bg-stone-100',
    chipBackground: 'bg-stone-100',
    foreground: 'text-stone-400',
  },
  {
    name: 'fighting',
    background: 'bg-red-400',
    backgroundOverlay: 'after:bg-red-100',
    chipBackground: 'bg-red-100',
    foreground: 'text-red-400',
  },
  {
    name: 'flying',
    background: 'bg-sky-400',
    backgroundOverlay: 'after:bg-sky-100',
    chipBackground: 'bg-sky-100',
    foreground: 'text-sky-400',
  },
  {
    name: 'poison',
    background: 'bg-purple-400',
    backgroundOverlay: 'after:bg-purple-100',
    chipBackground: 'bg-purple-100',
    foreground: 'text-purple-400',
  },
  {
    name: 'ground',
    background: 'bg-amber-400',
    backgroundOverlay: 'after:bg-amber-100',
    chipBackground: 'bg-amber-100',
    foreground: 'text-amber-400',
  },
  {
    name: 'rock',
    background: 'bg-orange-300',
    backgroundOverlay: 'after:bg-orange-100',
    chipBackground: 'bg-orange-100',
    foreground: 'text-orange-300',
  },
  {
    name: 'bug',
    background: 'bg-teal-400',
    backgroundOverlay: 'after:bg-teal-100',
    chipBackground: 'bg-teal-100',
    foreground: 'text-teal-400',
  },
  {
    name: 'ghost',
    background: 'bg-violet-400',
    backgroundOverlay: 'after:bg-violet-100',
    chipBackground: 'bg-violet-100',
    foreground: 'text-violet-400',
  },
  {
    name: 'steel',
    background: 'bg-slate-400',
    backgroundOverlay: 'after:bg-slate-100',
    chipBackground: 'bg-slate-100',
    foreground: 'text-slate-400',
  },
  {
    name: 'fire',
    background: 'bg-rose-400',
    backgroundOverlay: 'after:bg-rose-100',
    chipBackground: 'bg-rose-100',
    foreground: 'text-rose-400',
  },
  {
    name: 'water',
    background: 'bg-blue-400',
    backgroundOverlay: 'after:bg-blue-100',
    chipBackground: 'bg-blue-100',
    foreground: 'text-blue-400',
  },
  {
    name: 'grass',
    background: 'bg-emerald-400',
    backgroundOverlay: 'after:bg-emerald-100',
    chipBackground: 'bg-emerald-100',
    foreground: 'text-emerald-400',
  },
  {
    name: 'electric',
    background: 'bg-yellow-400',
    backgroundOverlay: 'after:bg-yellow-100',
    chipBackground: 'bg-yellow-100',
    foreground: 'text-yellow-400',
  },
  {
    name: 'psychic',
    background: 'bg-pink-400',
    backgroundOverlay: 'after:bg-pink-100',
    chipBackground: 'bg-pink-100',
    foreground: 'text-pink-400',
  },
  {
    name: 'ice',
    background: 'bg-cyan-300',
    backgroundOverlay: 'after:bg-cyan-100',
    chipBackground: 'bg-cyan-100',
    foreground: 'text-cyan-300',
  },
  {
    name: 'dragon',
    background: 'bg-indigo-400',
    backgroundOverlay: 'after:bg-indigo-100',
    chipBackground: 'bg-indigo-100',
    foreground: 'text-indigo-400',
  },
  {
    name: 'dark',
    background: 'bg-slate-600',
    backgroundOverlay: 'after:bg-slate-400',
    chipBackground: 'bg-slate-400',
    foreground: 'text-slate-600',
  },
  {
    name: 'fairy',
    background: 'bg-fuchsia-400',
    backgroundOverlay: 'after:bg-fuchsia-100',
    chipBackground: 'bg-fuchsia-100',
    foreground: 'text-fuchsia-400',
  },
  {
    name: 'stellar',
    background: 'bg-lime-300',
    backgroundOverlay: 'after:bg-lime-100',
    chipBackground: 'bg-lime-100',
    foreground: 'text-lime-300',
  },
  {
    name: 'unknown',
    background: 'bg-zinc-400',
    backgroundOverlay: 'after:bg-zinc-100',
    chipBackground: 'bg-zinc-100',
    foreground: 'text-zinc-400',
  },
  {
    name: 'shadow',
    background: 'bg-neutral-700',
    backgroundOverlay: 'after:bg-neutral-500',
    chipBackground: 'bg-neutral-500',
    foreground: 'text-neutral-700',
  },
];
